[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]   
repo = 'tpope/vim-fugitive'                                                                                                           
hook_add = """
source ~/.config/nvim/plugins/git-fugitive.rc.vim
"""

[[plugins]]   
repo = 'tpope/vim-surround'                                                                                                            

[[plugins]]   
repo = 'tpope/vim-commentary'

[[plugins]]   
repo = 'vim-airline/vim-airline'

[[plugins]]   
repo = 'vim-airline/vim-airline-themes'

[[plugins]]   
repo = 'sheerun/vim-polyglot'

[[plugins]]   
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]   
repo = 'ryanoasis/vim-devicons'

[[plugins]]   
repo = 'kristijanhusak/defx-icons'

[[plugins]]   
repo = 'kristijanhusak/defx-git'

[[plugins]]   
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]   
repo = 'Shougo/deoplete.nvim'
hook_add = """
source ~/.config/nvim/plugins/deoplete.rc.vim
"""

[[plugins]]   
repo = 'roxma/nvim-yarp'

[[plugins]]   
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]   
repo = 'reireias/vim-cheatsheet'

[[plugins]]   
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]   
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

[[plugins]]   
repo = 'alvan/vim-closetag'
